apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: Pe7atN/devops-backend:latest 
        ports:
        - containerPort: 3000
        env:
        # Pulling from ConfigMap (db-config)
        - name: DB_HOST
          valueFrom: { configMapKeyRef: { name: db-config, key: DB_HOST } }
        - name: DB_USER
          valueFrom: { configMapKeyRef: { name: db-config, key: DB_USER } }
        - name: DB_NAME
          valueFrom: { configMapKeyRef: { name: db-config, key: DB_NAME } }
        - name: DB_PORT
          value: "5432"
        # Pulling from Secret (db-secret)
        - name: DB_PASSWORD
          valueFrom: { secretKeyRef: { name: db-secret, key: DB_PASSWORD } }
        livenessProbe:
          httpGet:
            path: /api/cities
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /api/cities
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000