apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  DB_NAME: "city_db"
  DB_USER: "postgres"
  DB_HOST: "postgres-service"
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  DB_PASSWORD: cGFzc3dvcmQ=